# Use root/example as user/password credentials
version: '3.9'

services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'tqsdemo'
      MYSQL_USER: 'tqsdemo'
      MYSQL_PASSWORD: 'tqsdemo'
      MYSQL_DATABASE: 'tqsdemo'
    ports:
      - 3306:3306
